//! report.rs — Formatter emitting org-wide executive Markdown, JSON, and summary text.

use crate::enrich::EnrichedHall;

pub fn emit_markdown(hall: &EnrichedHall) -> String {
    let mut out = String::new();
    out.push_str(&format!("# Boneyard Report — Org Tech-Debt Radar (`{}`)\n\n", hall.org_name));
    out.push_str("> Generated by [Boneyard](https://studio2201.com/boneyard) · studio2201\n\n");
    out.push_str(&format!(
        "**Total Repositories**: {}  \n**Average Boneyard Index**: {:.1}/100  \n**Total Remediation Budget**: {:.1} repo-weeks\n\n",
        hall.total_repos, hall.avg_boneyard_index, hall.total_remediation_weeks
    ));

    out.push_str("### Executive Summary\n\n");
    out.push_str("| Metric | Count |\n| :--- | :--- |\n");
    out.push_str(&format!("| 🔴 Critical Tech-Debt (Index ≥ 75) | {} |\n", hall.critical_count));
    out.push_str(&format!("| 🟠 High Tech-Debt (Index 55–74) | {} |\n", hall.high_count));
    out.push_str(&format!("| 🟢 Healthy / Low Tech-Debt | {} |\n\n", hall.total_repos.saturating_sub(hall.critical_count + hall.high_count)));

    out.push_str("### Repository Ranked Index\n\n");
    out.push_str("| Repository | Visibility | Dormancy | Transitive Deps | Bot Commits | Boneyard Index | Remediation | Recommended Action |\n");
    out.push_str("| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |\n");

    for r in &hall.repos {
        let vis = if r.repo.is_public { "Public" } else { "Private" };
        out.push_str(&format!(
            "| `{}` | {} | {}d | {} | {:.0}% | **{:.1}** | {:.1}w | {} |\n",
            r.repo.name, vis, r.repo.days_dormant, r.repo.dependency_count,
            r.repo.recent_bot_commit_pct * 100.0, r.boneyard_index,
            r.remediation_weeks, r.recommendation
        ));
    }

    out
}

pub fn emit_json(hall: &EnrichedHall) -> String {
    let mut out = String::new();
    out.push_str("{\n");
    out.push_str(&format!("  \"org_name\": \"{}\",\n", hall.org_name));
    out.push_str(&format!("  \"total_repos\": {},\n", hall.total_repos));
    out.push_str(&format!("  \"avg_boneyard_index\": {:.2},\n", hall.avg_boneyard_index));
    out.push_str(&format!("  \"total_remediation_weeks\": {:.2},\n", hall.total_remediation_weeks));
    out.push_str(&format!("  \"critical_count\": {},\n", hall.critical_count));
    out.push_str(&format!("  \"high_count\": {},\n", hall.high_count));
    out.push_str("  \"repositories\": [\n");

    for (i, r) in hall.repos.iter().enumerate() {
        let comma = if i + 1 < hall.repos.len() { "," } else { "" };
        out.push_str(&format!(
            "    {{\"name\": \"{}\", \"is_public\": {}, \"days_dormant\": {}, \"boneyard_index\": {:.2}, \"remediation_weeks\": {:.2}, \"recommendation\": \"{}\"}}{}\n",
            r.repo.name, r.repo.is_public, r.repo.days_dormant, r.boneyard_index, r.remediation_weeks, r.recommendation, comma
        ));
    }

    out.push_str("  ]\n");
    out.push_str("}\n");
    out
}

pub fn emit_text(hall: &EnrichedHall) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "boneyard: org '{}' ({} repos) | Avg Index: {:.1} | Total Remediation: {:.1} repo-weeks\n",
        hall.org_name, hall.total_repos, hall.avg_boneyard_index, hall.total_remediation_weeks
    ));
    out.push_str(&format!(
        "Critical: {} | High: {} | Healthy: {}\n",
        hall.critical_count, hall.high_count, hall.total_repos.saturating_sub(hall.critical_count + hall.high_count)
    ));
    for r in hall.repos.iter().take(5) {
        out.push_str(&format!(
            "  [{:.1}] {:<24} -> {}\n",
            r.boneyard_index, r.repo.name, r.recommendation
        ));
    }
    if hall.repos.len() > 5 {
        out.push_str(&format!("  ... and {} more repositories\n", hall.repos.len() - 5));
    }
    out
}
